### ISSUE TITLE
Names for External Guest Users

### ISSUE THREAD

**Issue by gary-kim** [gary-kim/go-nc-talk#17]
When a guest joins a public ally accessible room in Talk, the display name does not display `(Guest)`. 

It is currently not possible to figure out if a user is a guest or user on the instance so this should be added. Once that's added, projects using the library can use that information to append `(Guest)` for guest users.

It could also be useful to add a `DisplayName()` function that will automatically append `(Guest)`.

https://github.com/gary-kim/go-nc-talk/blob/ee3c5d2f49e768b75b9f3de80bfa738bf2a61710/ocs/message.go#L36-L46

cc @nickvergessen

**Comment by nickvergessen** [comment]
Pseudo code:
```
if ActorID starts with guest/ then
  if ActorDisplayName.empty then
    return 'Guest'
  else
    return ActorDisplayName.append(' (Guest)')
  fi
else
// current handling
fi
```

**Comment by gary-kim** [comment]
That'd be good. I was thinking we could also add the `actorType` field as a `ActorType` type.
