### ISSUE TITLE
Double Slash in URLs

### ISSUE THREAD

**Issue by gary-kim** [gary-kim/go-nc-talk#22]
There are double slashes in some of the urls to which requests are being made.
```
0.0.0.0 - - [21/Sep/2020:14:07:18 +0000] "GET /ocs/v2.php/apps/spreed/api/v1//chat/dhwk73nv?includeLastKnown=0&lastKnownMessageId=0&lookIntoFuture=1 HTTP/1.1" 304 4932 "-" "Go-http-client/1.1" 0
```

It should be pretty easy to fix this issue here:
https://github.com/gary-kim/go-nc-talk/blob/eb84ad347371691a29f3a1573197ed817624228c/room/room.go#L96
https://github.com/gary-kim/go-nc-talk/blob/eb84ad347371691a29f3a1573197ed817624228c/room/room.go#L65

**Comment by u5surf** [comment]
@gary-kim I’d like to work on this issue.

**Comment by gary-kim** [comment]
You are perfectly welcome to!
